---
# Переменные для настройки DHCP

# Диапазон исключенных IP-адресов (например, для статичных IP или устройств, которым не нужно получать DHCP)
dhcp_excluded_addresses:
  - "10.20.1.1 10.20.1.50"
  - "10.20.1.100 10.20.1.254"

# Переменные для настройки DHCP пулов
dhcp_pools:
  - name: "VLAN_20"
    network: "10.20.1.0 255.255.255.0"
    default_router: "10.20.1.1"
    dns_server: "8.8.8.8"


